### ISSUE TITLE
Config flow could not be loaded

### ISSUE THREAD

**Issue by goven** [georgezhao2010/apple_airplayer#1]
When add this integration, error popped with Config flow could not be loaded, and fail to add this integration. homeassistant version 2021.7.3.

**Comment by georgezhao2010** [comment]
There are some bugs in Home Assisatant 2021.7x or later, please see the link below

https://github.com/georgezhao2010/apple_airplayer/blob/master/README.md#20217-x-or-later

**Comment by georgezhao2010** [comment]
> When add this integration, error popped with Config flow could not be loaded, and fail to add this integration. homeassistant version 2021.7.3.

There are some bugs in Home Assisatant 2021.7x or later, please see the link below

https://github.com/georgezhao2010/apple_airplayer/blob/master/README.md#20217-x-or-later

**Comment by goven** [comment]
Thanks, but I'm using Home Assistant OS 6.2, could you tell me how to execute these commands in Home Assistant OS?

**Comment by goven** [comment]
I found the host system is alpine, I use 'apk add python3' and 'apk add py3-pip' to install python3 and pip3, then I use 'pip3 install miniaudio' to install miniaudio, but errors came out, and I can't install miniaudio.

**Comment by bossben8** [comment]
The playback of tts is not smooth, and the log appears a lot
2021-08-08 00:30:41 WARNING (MainThread) [pyatv.raop.raop] Too slow to keep up for seqno 39971 (0.957823 vs 0.959274 => -0.001451)
2021-08-08 00:30:41 WARNING (MainThread) [pyatv.raop.raop] Too slow to keep up for seqno 39972 (0.965805 vs 0.966809 => -0.001004)
2021-08-08 00:30:46 WARNING (MainThread) [pyatv.raop.raop] Too slow to keep up for seqno 39977 (1.005714 vs 6.091000 => -5.085286)
2021-08-08 00:30:46 WARNING (MainThread) [pyatv.raop.raop] Too slow to keep up for seqno 39981 (1.037642 vs 6.123049 => -5.085407)
2021-08-08 00:30:46 WARNING (MainThread) [pyatv.raop.raop] Too slow to keep up for seqno 39985 (1.069569 vs 6.153714 => -5.084145)
2021-08-08 00:30:46 WARNING (MainThread) [pyatv.raop.raop] Too slow to keep up for seqno 39989 (1.101497 vs 6.176565 => -5.075069)
2021-08-08 00:30:46 WARNING (MainThread) [pyatv.raop.raop] Too slow to keep up for seqno 39993 (1.133424 vs 6.192660 => -5.059236)
2021-08-08 00:30:46 WARNING (MainThread) [pyatv.raop.raop] Too slow to keep up for seqno 39997 (1.165351 vs 6.208388 => -5.043037)
2021-08-08 00:30:46 WARNING (MainThread) [pyatv.raop.raop] Too slow to keep up for seqno 40001 (1.197279 vs 6.224719 => -5.027440)
2021-08-08 00:30:46 WARNING (MainThread) [pyatv.raop.raop] Too slow to keep up for seqno 40005 (1.229206 vs 6.240557 => -5.011350)
2021-08-08 00:30:46 WARNING (MainThread) [pyatv.raop.raop] Too slow to keep up for seqno 40009 (1.261134 vs 6.256408 => -4.995274)
2021-08-08 00:30:46 WARNING (MainThread) [pyatv.raop.raop] Too slow to keep up for seqno 40013 (1.293061 vs 6.272875 => -4.979813)
2021-08-08 00:30:46 WARNING (MainThread) [pyatv.raop.raop] Too slow to keep up for seqno 40017 (1.324989 vs 6.289230 => -4.964241)
2021-08-08 00:30:46 WARNING (MainThread) [pyatv.raop.raop] Too slow to keep up for seqno 40021 (1.356916 vs 6.305423 => -4.948507)
2021-08-08 00:30:46 WARNING (MainThread) [pyatv.raop.raop] Too slow to keep up for seqno 40025 (1.388844 vs 6.321442 => -4.932598)
2021-08-08 00:30:46 WARNING (MainThread) [pyatv.raop.raop] Too slow to keep up for seqno 40029 (1.420771 vs 6.338121 => -4.917350)
2021-08-08 00:30:46 WARNING (MainThread) [pyatv.raop.raop] Too slow to keep up for seqno 40033 (1.452698 vs 6.353921 => -4.901222)
2021-08-08 00:30:46 WARNING (MainThread) [pyatv.raop.raop] Too slow to keep up for seqno 40037 (1.484626 vs 6.369991 => -4.885366)

**Comment by goven** [comment]
> The playback of tts is not smooth, and the log appears a lot
> 
> 2021-08-08 00:30:41 WARNING (MainThread) [pyatv.raop.raop] Too slow to keep up for seqno 39971 (0.957823 vs 0.959274 => -0.001451)
> 
> 2021-08-08 00:30:41 WARNING (MainThread) [pyatv.raop.raop] Too slow to keep up for seqno 39972 (0.965805 vs 0.966809 => -0.001004)
> 
> 2021-08-08 00:30:46 WARNING (MainThread) [pyatv.raop.raop] Too slow to keep up for seqno 39977 (1.005714 vs 6.091000 => -5.085286)
> 
> 2021-08-08 00:30:46 WARNING (MainThread) [pyatv.raop.raop] Too slow to keep up for seqno 39981 (1.037642 vs 6.123049 => -5.085407)
> 
> 2021-08-08 00:30:46 WARNING (MainThread) [pyatv.raop.raop] Too slow to keep up for seqno 39985 (1.069569 vs 6.153714 => -5.084145)
> 
> 2021-08-08 00:30:46 WARNING (MainThread) [pyatv.raop.raop] Too slow to keep up for seqno 39989 (1.101497 vs 6.176565 => -5.075069)
> 
> 2021-08-08 00:30:46 WARNING (MainThread) [pyatv.raop.raop] Too slow to keep up for seqno 39993 (1.133424 vs 6.192660 => -5.059236)
> 
> 2021-08-08 00:30:46 WARNING (MainThread) [pyatv.raop.raop] Too slow to keep up for seqno 39997 (1.165351 vs 6.208388 => -5.043037)
> 
> 2021-08-08 00:30:46 WARNING (MainThread) [pyatv.raop.raop] Too slow to keep up for seqno 40001 (1.197279 vs 6.224719 => -5.027440)
> 
> 2021-08-08 00:30:46 WARNING (MainThread) [pyatv.raop.raop] Too slow to keep up for seqno 40005 (1.229206 vs 6.240557 => -5.011350)
> 
> 2021-08-08 00:30:46 WARNING (MainThread) [pyatv.raop.raop] Too slow to keep up for seqno 40009 (1.261134 vs 6.256408 => -4.995274)
> 
> 2021-08-08 00:30:46 WARNING (MainThread) [pyatv.raop.raop] Too slow to keep up for seqno 40013 (1.293061 vs 6.272875 => -4.979813)
> 
> 2021-08-08 00:30:46 WARNING (MainThread) [pyatv.raop.raop] Too slow to keep up for seqno 40017 (1.324989 vs 6.289230 => -4.964241)
> 
> 2021-08-08 00:30:46 WARNING (MainThread) [pyatv.raop.raop] Too slow to keep up for seqno 40021 (1.356916 vs 6.305423 => -4.948507)
> 
> 2021-08-08 00:30:46 WARNING (MainThread) [pyatv.raop.raop] Too slow to keep up for seqno 40025 (1.388844 vs 6.321442 => -4.932598)
> 
> 2021-08-08 00:30:46 WARNING (MainThread) [pyatv.raop.raop] Too slow to keep up for seqno 40029 (1.420771 vs 6.338121 => -4.917350)
> 
> 2021-08-08 00:30:46 WARNING (MainThread) [pyatv.raop.raop] Too slow to keep up for seqno 40033 (1.452698 vs 6.353921 => -4.901222)
> 
> 2021-08-08 00:30:46 WARNING (MainThread) [pyatv.raop.raop] Too slow to keep up for seqno 40037 (1.484626 vs 6.369991 => -4.885366)

You can open another issue, bro

**Comment by georgezhao2010** [comment]
> I found the host system is alpine, I use 'apk add python3' and 'apk add py3-pip' to install python3 and pip3, then I use 'pip3 install miniaudio' to install miniaudio, but errors came out, and I can't install miniaudio.

Python3 is already included in HASSOS, run follow commands as below:

```
apk update
apk add build-base
pip3 uninstall --yes miniaudio
pip3 install miniaudio
```

> I found the host system is alpine, I use 'apk add python3' and 'apk add py3-pip' to install python3 and pip3, then I use 'pip3 install miniaudio' to install miniaudio, but errors came out, and I can't install miniaudio.

Python3 is already included in HASSOS, run follow commands as below:

```
apk update
apk add build-base
pip3 uninstall --yes miniaudio
pip3 install miniaudio
```

**Comment by goven** [comment]
Home Assistant OS did not preinstalled Python3 or miniaudio, First I have to install Python3 and pip3, after that when I use pip3 to install miniaudio, get these errors.
![Untitled](https://user-images.githubusercontent.com/732774/128980926-f96cf94d-33a4-4fd2-805e-2e9c6a4ff1c1.png)

**Comment by georgezhao2010** [comment]
> Home Assistant OS did not preinstalled Python3 or miniaudio, First I have to install Python3 and pip3, after that when I use pip3 to install miniaudio, get these errors.

I don't 

Show me your HA system info in http://{Your_HA_IP_Address}:8123/config/info

Like this

```
System Health

version: core-2021.8.4
installation_type: Home Assistant Container
dev: false
hassio: false
docker: true
user: root
virtualenv: false
python_version: 3.9.6
os_name: Linux
os_version: 4.4.59+
arch: x86_64
timezone: Asia/Shanghai

GitHub API: ok
Github API Calls Remaining: 5000
Installed Version: 1.13.2
Stage: running
Available Repositories: 851
Installed Repositories: 20

logged_in: false
can_reach_cert_server: ok
can_reach_cloud_auth: ok
can_reach_cloud: ok

dashboards: 1
resources: 6
views: 9
mode: storage

logged_in: true
can_reach_micloud_server: ok
accounts_count: 1
account_devices_count: 14
added_devices: 2
```

**Comment by goven** [comment]
## System Health

version | core-2021.8.6
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.6
os_name | Linux
os_version | 5.10.53
arch | x86_64
timezone | Asia/Hong_Kong

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4979
Installed Version | 1.13.2
Stage | running
Available Repositories | 844
Installed Repositories | 3

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | November 17, 2018, 8:00 AM
relayer_connected | false
remote_enabled | true
remote_connected | false
alexa_enabled | false
google_enabled | false
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.2
-- | --
update_channel | stable
supervisor_version | supervisor-2021.06.8
docker_version | 20.10.6
disk_total | 38.7 GB
disk_used | 7.7 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.3.3), Node-RED (10.0.0), RPC Shutdown (2.2), Samba share (9.2.0), Terminal & SSH (9.1.3)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 0
views | 1
mode | storage

</details>

**Comment by georgezhao2010** [comment]
> ## System Health
> version	core-2021.8.6
> installation_type	Home Assistant OS
> ...

See, I'm sure the Python 3.9.6 has been already installed in HASSOS.

Follow the steps below

- Start 'SSH & Web Terminal'.
- Open WEB-UI of 'SSH & Web Terminal'.
- In terminal, run following commands
```
docker exec -it homeassistant /bin/bash
apk update
apk add build-base
pip3 uninstall --yes miniaudio
pip3 install miniaudio
```
in command `docker exec -it homeassistant /bin/bash`, homeassistant is your HA docker's name.
- Restart HASSOS

**Comment by goven** [comment]
~$ docker
bash: docker: command not found

**Comment by steve41200** [comment]
I have exactly the same problem. I have try via the way you propose (terminal) and have the same pb than goven.
Before see your answer I have make some try. I have HASSOS install via proxmox I have try via the proxmox shell and via SSH with the root account

**Comment by goven** [comment]
> I have exactly the same problem. I have try via the way you propose (terminal) and have the same pb than goven.
> 
> Before see your answer I have make some try. I have HASSOS install via proxmox I have try via the proxmox shell and via SSH with the root account
> 
> 

My HASSOS also installed on a virtual machine of Proxmox, we have the same issue,maybe this problem happened only on HOMEASSISTANT OS.

**Comment by steve41200** [comment]
may be I'm not a pro in linux line command, but the author is in Home Assistant container and not home assistant OS, maybe a way to understand the problem

**Comment by steve41200** [comment]
It works to me.
On Proxmox, run the shell windows (on the top of the HASSOS VM)
Type login
root
(no password require)
and after run the line of George
docker exec -it homeassistant /bin/bash
apk update
apk add build-base
pip3 uninstall --yes miniaudio
pip3 install miniaudio

the first line put a bash5 before each line. I don't understand very well linux specificity but it does the job. 
TY for the author I search an add on like this since a long long time, and I have try some off technic without success

And for the little story I have try this during I occuping the kids, and I promise them to choose the first sentence of Siri, it was choose "Prout caca Boudin" I don't know the English equivalence :)

**Comment by goven** [comment]
> It works to me.
> 
> On Proxmox, run the shell windows (on the top of the HASSOS VM)
> 
> Type login
> 
> root
> 
> (no password require)
> 
> and after run the line of George
> 
> docker exec -it homeassistant /bin/bash
> 
> apk update
> 
> apk add build-base
> 
> pip3 uninstall --yes miniaudio
> 
> pip3 install miniaudio
> 
> 
> 
> the first line put a bash5 before each line. I don't understand very well linux specificity but it does the job. 
> 
> TY for the author I search an add on like this since a long long time, and I have try some off technic without success
> 
> 
> 
> And for the little story I have try this during I occuping the kids, and I promise them to choose the first sentence of Siri, it was choose "Prout caca Boudin" I don't know the English equivalence :)
> 
> 
> 
> 

These commands works for me and miniaudio was installed, but I still fail to add Apple AirPlayer in integrations with the same error.

**Comment by georgezhao2010** [comment]
> > It works to me.
> > On Proxmox, run the shell windows (on the top of the HASSOS VM)
> > Type login
> > root
> > (no password require)
> > and after run the line of George
> > docker exec -it homeassistant /bin/bash
> > apk update
> > apk add build-base
> > pip3 uninstall --yes miniaudio
> > pip3 install miniaudio
> > the first line put a bash5 before each line. I don't understand very well linux specificity but it does the job.
> > TY for the author I search an add on like this since a long long time, and I have try some off technic without success
> > And for the little story I have try this during I occuping the kids, and I promise them to choose the first sentence of Siri, it was choose "Prout caca Boudin" I don't know the English equivalence :)
> 
> These commands works for me and miniaudio was installed, but I still fail to add Apple AirPlayer in integrations with the same error.![image](https://user-images.githubusercontent.com/732774/129452069-3b375d60-e31f-4eed-95a8-48beeb8a9056.png)
> 
> By the way, you can speak Chinese,I'm Chinese.

Any logs when config failure?

**Comment by goven** [comment]
This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/apple_airplayer/device_manager.py:9
Integration: Apple AirPlayer (documentation, issues) 
First occurred: 9:23:34 AM (1 occurrences) 
Last logged: 9:23:34 AM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 84, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 128, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 63, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 72, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 153, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 171, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 696, in async_create_flow
    integration.get_platform("config_flow")
  File "/usr/src/homeassistant/homeassistant/loader.py", line 498, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 503, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/apple_airplayer/config_flow.py", line 5, in <module>
    from .device_manager import DeviceManager
  File "/config/custom_components/apple_airplayer/device_manager.py", line 9, in <module>
    DeviceModel.AirPortExpress: "AirPort Express",
  File "/usr/local/lib/python3.9/enum.py", line 429, in __getattr__
    raise AttributeError(name) from None
AttributeError: AirPortExpress

**Comment by goven** [comment]
> > > It works to me.
> 
> > > On Proxmox, run the shell windows (on the top of the HASSOS VM)
> 
> > > Type login
> 
> > > root
> 
> > > (no password require)
> 
> > > and after run the line of George
> 
> > > docker exec -it homeassistant /bin/bash
> 
> > > apk update
> 
> > > apk add build-base
> 
> > > pip3 uninstall --yes miniaudio
> 
> > > pip3 install miniaudio
> 
> > > the first line put a bash5 before each line. I don't understand very well linux specificity but it does the job.
> 
> > > TY for the author I search an add on like this since a long long time, and I have try some off technic without success
> 
> > > And for the little story I have try this during I occuping the kids, and I promise them to choose the first sentence of Siri, it was choose "Prout caca Boudin" I don't know the English equivalence :)
> 
> > 
> 
> > These commands works for me and miniaudio was installed, but I still fail to add Apple AirPlayer in integrations with the same error.!
> 
> > 
> 
> > By the way, you can speak Chinese,I'm Chinese.
> 
> 
> 
> Any logs when config failure?

This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/apple_airplayer/device_manager.py:9
Integration: Apple AirPlayer (documentation, issues) 
First occurred: 9:23:34 AM (1 occurrences) 
Last logged: 9:23:34 AM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 84, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 128, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 63, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 72, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 153, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 171, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 696, in async_create_flow
    integration.get_platform("config_flow")
  File "/usr/src/homeassistant/homeassistant/loader.py", line 498, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 503, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/apple_airplayer/config_flow.py", line 5, in <module>
    from .device_manager import DeviceManager
  File "/config/custom_components/apple_airplayer/device_manager.py", line 9, in <module>
    DeviceModel.AirPortExpress: "AirPort Express",
  File "/usr/local/lib/python3.9/enum.py", line 429, in __getattr__
    raise AttributeError(name) from None
AttributeError: AirPortExpress

**Comment by georgezhao2010** [comment]
> This error originated from a custom integration.
> 
> Logger: aiohttp.server
> Source: custom_components/apple_airplayer/device_manager.py:9
> Integration: Apple AirPlayer (documentation, issues)
> First occurred: 9:23:34 AM (1 occurrences)
> Last logged: 9:23:34 AM
> 
> ...
>
> File "/usr/local/lib/python3.9/enum.py", line 429, in **getattr**
> raise AttributeError(name) from None
> AttributeError: AirPortExpress

In HASSOS Terminal, run `pip3 list | grep pyatv` to confirm the version of pyatv.

try run `pip3 install --upgrade pyatv`  to upgrade pyatv

If you are a Chinese, visit this link to find out more information about config error. [让你的HomePod可以TTS？没有那么多麻烦](https://bbs.hassbian.com/thread-13513-1-1.html)

**Comment by goven** [comment]
> > This error originated from a custom integration.
> > Logger: aiohttp.server
> > Source: custom_components/apple_airplayer/device_manager.py:9
> > Integration: Apple AirPlayer (documentation, issues)
> > First occurred: 9:23:34 AM (1 occurrences)
> > Last logged: 9:23:34 AM
> > ...
> > File "/usr/local/lib/python3.9/enum.py", line 429, in **getattr**
> > raise AttributeError(name) from None
> > AttributeError: AirPortExpress
> 
> In HASSOS Terminal, run `pip3 list | grep pyatv` to confirm the version of pyatv.
> 
> Run `pip3 install --upgrade pyatv` to upgrade pyatv
> 
> If you are a Chinese, visit this link to find out more information about config error. [让你的HomePod可以TTS？没有那么多麻烦](https://bbs.hassbian.com/thread-13513-1-1.html)

I don't find the same situation as mine there, could you add my qq(1021073979) to help me with this problem? thanks!

**Comment by goven** [comment]
With this author's help, I finally got this problem solved after I removed a custom integration named Apple TV from HACS.

**Comment by georgezhao2010** [comment]
The  old version [Apple TV integration ](https://github.com/postlund/hass-atv-beta) manifesting `pyatv=0.7.7` in file manifest.json, conflicts with this integration. If you want tp setup Apple TV integration, you should install official components from Home Assistant  of latest version.
