### ISSUE TITLE
Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by Douganatornz** [georgezhao2010/apple_airplayer#25]
I'm getting this error message in the log over a 1000 times a day. Any idea what may be causing this issue?

> Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 735, in _update_entity_states
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 574, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 934, in state_attributes
    if (value := getattr(self, attr)) is not None:
  File "/config/custom_components/apple_airplayer/media_player.py", line 59, in volume_level
    return self._player_device.volume_level
  File "/config/custom_components/apple_airplayer/device_manager.py", line 80, in volume_level
    return self._atv_interface.audio.volume / 100
  File "/usr/local/lib/python3.9/site-packages/pyatv/support/shield.py", line 71, in _guard_method
    raise BlockedStateError(f"{func.__name__} is blocked")
pyatv.exceptions.BlockedStateError: audio is blocked

>

**Comment by mantos730** [comment]
I have same issue. I am not sure because my internet is reconnected.

Logger: homeassistant
Source: custom_components/apple_airplayer/device_manager.py:80
Integration: Apple AirPlayer ([documentation](https://github.com/georgezhao2010/apple_airplayer), [issues](https://github.com/georgezhao2010/apple_airplayer/issue))
First occurred: 2022年5月15日 20:55:21 (11477 occurrences)
Last logged: 12:51:52

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 735, in _update_entity_states
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 519, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 572, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 936, in state_attributes
    if (value := getattr(self, attr)) is not None:
  File "/config/custom_components/apple_airplayer/media_player.py", line 59, in volume_level
    return self._player_device.volume_level
  File "/config/custom_components/apple_airplayer/device_manager.py", line 80, in volume_level
    return self._atv_interface.audio.volume / 100
  File "/usr/local/lib/python3.9/site-packages/pyatv/support/shield.py", line 71, in _guard_method
    raise BlockedStateError(f"{func.__name__} is blocked")
pyatv.exceptions.BlockedStateError: audio is blocked
