### ISSUE TITLE
No TTS after Home Assistant Core upgrade to v2022-5-0

### ISSUE THREAD

**Issue by nimroddolev** [georgezhao2010/apple_airplayer#28]
I have been unable to play TTS on my HomePod Mini after upgrading my RPi4 to Home Assistant core v2022-5.0.

My error log message from Home Assistant:

```This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/apple_airplayer/media_player.py:110
Integration: Apple AirPlayer (documentation, issues)
First occurred: May 7, 2022, 11:33:18 PM (2 occurrences)
Last logged: 9:32:11 AM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/apple_airplayer/media_player.py", line 110, in async_play_stream
    r = await session.get(url)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1146, in _create_direct_connection
    assert port is not None
AssertionError

**Comment by kyle2207** [comment]
我也是有相同的問題，我的home assistant core 是 v2022 5.3

Logger: homeassistant
Source: custom_components/apple_airplayer/media_player.py:110
Integration: Apple AirPlayer ([documentation](https://github.com/georgezhao2010/apple_airplayer), [issues](https://github.com/georgezhao2010/apple_airplayer/issue))
First occurred: 01:59:55 (9 occurrences)
Last logged: 02:50:08

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/apple_airplayer/media_player.py", line 110, in async_play_stream
    r = await session.get(url)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1146, in _create_direct_connection
    assert port is not None
AssertionError
